[options]
; Rutas verificadas para el repo de Bytedav
addons_path = /opt/odoo/enterprise,/opt/odoo/odoo/addons,/opt/odoo/addons
data_dir = /var/lib/odoo
admin_passwd = ${ADMIN_PASSWORD}

; Configuración de red para producción
proxy_mode = True
xmlrpc_interface = 0.0.0.0
netrpc_interface = 0.0.0.0

; Rendimiento para Producción (basado en un servidor de 2-4 núcleos)
workers = 4
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_request = 8192
limit_time_cpu = 600
limit_time_real = 1200
max_cron_threads = 1
